model:
  type: swin
  name: swin_base_patch4_window7_224
  drop_path_rate: 0.5
  drop_rate: 0.3
  num_classes: 10
  swin:
    embed_dim: 96
    depths: [ 2, 2, 6, 2 ]
    num_heads: [ 3, 6, 12, 24 ]
    window_size: 7
    patch_size: 4
    in_chans: 1
    mlp_ratio: 4.
    qkv_bias: True
    qk_scale: None
    ape: False
    patch_norm: True
data:
  img_size: 224
train:
  use_checkpoint: False

