MODEL:
  TYPE: swin_mlp
  NAME: swin_mlp_base_patch4_window7_224
  DROP_PATH_RATE: 0.5
  NUM_CLASSES: 1000
  DROP_RATE: 0.
  SWIN_MLP:
    EMBED_DIM: 128
    DEPTHS: [ 2, 2, 18, 2 ]
    NUM_HEADS: [ 4, 8, 16, 32 ]
    WINDOW_SIZE: 7
    PATCH_SIZE: 4
    IN_CHANS: 3
    MLP_RATIO: 4.
    APE: False
    PATCH_NORM: True
DATA:
  IMG_SIZE: 224
TRAIN:
  USE_CHECKPOINT: False